/**
 * Specification API Backend ImmoAlerte.fr
 * Specification API Backend ImmoAlerte.fr
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Jacques.cortes@elasticsolutions.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpecificationApiBackendImmoAlertefr) {
      root.SpecificationApiBackendImmoAlertefr = {};
    }
    root.SpecificationApiBackendImmoAlertefr.UserCoordonnees = factory(root.SpecificationApiBackendImmoAlertefr.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserCoordonnees model module.
   * @module model/UserCoordonnees
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserCoordonnees</code>.
   * @alias module:model/UserCoordonnees
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>UserCoordonnees</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserCoordonnees} obj Optional instance to populate.
   * @return {module:model/UserCoordonnees} The populated <code>UserCoordonnees</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('civilite')) {
        obj['civilite'] = ApiClient.convertToType(data['civilite'], 'String');
      }
      if (data.hasOwnProperty('nom')) {
        obj['nom'] = ApiClient.convertToType(data['nom'], 'String');
      }
      if (data.hasOwnProperty('prenom')) {
        obj['prenom'] = ApiClient.convertToType(data['prenom'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('numTel')) {
        obj['numTel'] = ApiClient.convertToType(data['numTel'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/UserCoordonnees.CiviliteEnum} civilite
   */
  exports.prototype['civilite'] = undefined;
  /**
   * @member {String} nom
   */
  exports.prototype['nom'] = undefined;
  /**
   * @member {String} prenom
   */
  exports.prototype['prenom'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} numTel
   */
  exports.prototype['numTel'] = undefined;


  /**
   * Allowed values for the <code>civilite</code> property.
   * @enum {String}
   * @readonly
   */
  exports.CiviliteEnum = {
    /**
     * value: "Mr"
     * @const
     */
    "Mr": "Mr",
    /**
     * value: "Mme"
     * @const
     */
    "Mme": "Mme",
    /**
     * value: "Mlle"
     * @const
     */
    "Mlle": "Mlle"  };


  return exports;
}));


