/**
 * Specification API Backend ImmoAlerte.fr
 * Specification API Backend ImmoAlerte.fr
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Jacques.cortes@elasticsolutions.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SpecificationApiBackendImmoAlertefr) {
      root.SpecificationApiBackendImmoAlertefr = {};
    }
    root.SpecificationApiBackendImmoAlertefr.UserAbonnement = factory(root.SpecificationApiBackendImmoAlertefr.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UserAbonnement model module.
   * @module model/UserAbonnement
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>UserAbonnement</code>.
   * @alias module:model/UserAbonnement
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>UserAbonnement</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserAbonnement} obj Optional instance to populate.
   * @return {module:model/UserAbonnement} The populated <code>UserAbonnement</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('statutAbonnement')) {
        obj['statutAbonnement'] = ApiClient.convertToType(data['statutAbonnement'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/UserAbonnement.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/UserAbonnement.StatutAbonnementEnum} statutAbonnement
   */
  exports.prototype['statutAbonnement'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "essentiel"
     * @const
     */
    "essentiel": "essentiel",
    /**
     * value: "standard"
     * @const
     */
    "standard": "standard",
    /**
     * value: "premium"
     * @const
     */
    "premium": "premium"  };

  /**
   * Allowed values for the <code>statutAbonnement</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StatutAbonnementEnum = {
    /**
     * value: "run"
     * @const
     */
    "run": "run",
    /**
     * value: "stop"
     * @const
     */
    "stop": "stop"  };


  return exports;
}));


