/**
 * Specification API Backend ImmoAlerte.fr
 * Specification API Backend ImmoAlerte.fr
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Jacques.cortes@elasticsolutions.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserAbonnement', 'model/UserCoordonnees'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserAbonnement'), require('./UserCoordonnees'));
  } else {
    // Browser globals (root is window)
    if (!root.SpecificationApiBackendImmoAlertefr) {
      root.SpecificationApiBackendImmoAlertefr = {};
    }
    root.SpecificationApiBackendImmoAlertefr.User = factory(root.SpecificationApiBackendImmoAlertefr.ApiClient, root.SpecificationApiBackendImmoAlertefr.UserAbonnement, root.SpecificationApiBackendImmoAlertefr.UserCoordonnees);
  }
}(this, function(ApiClient, UserAbonnement, UserCoordonnees) {
  'use strict';




  /**
   * The User model module.
   * @module model/User
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('passwd')) {
        obj['passwd'] = ApiClient.convertToType(data['passwd'], 'String');
      }
      if (data.hasOwnProperty('coordonnees')) {
        obj['coordonnees'] = UserCoordonnees.constructFromObject(data['coordonnees']);
      }
      if (data.hasOwnProperty('abonnement')) {
        obj['abonnement'] = UserAbonnement.constructFromObject(data['abonnement']);
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} passwd
   */
  exports.prototype['passwd'] = undefined;
  /**
   * @member {module:model/UserCoordonnees} coordonnees
   */
  exports.prototype['coordonnees'] = undefined;
  /**
   * @member {module:model/UserAbonnement} abonnement
   */
  exports.prototype['abonnement'] = undefined;



  return exports;
}));


