/**
 * Specification API Backend ImmoAlerte.fr
 * Specification API Backend ImmoAlerte.fr
 *
 * OpenAPI spec version: 1.0.0
 * Contact: Jacques.cortes@elasticsolutions.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SpecificationApiBackendImmoAlertefr);
  }
}(this, function(expect, SpecificationApiBackendImmoAlertefr) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SpecificationApiBackendImmoAlertefr.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('alerteCreate', function() {
      it('should call alerteCreate successfully', function(done) {
        //uncomment below and update the code to test alerteCreate
        //instance.alerteCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('alerteDelete', function() {
      it('should call alerteDelete successfully', function(done) {
        //uncomment below and update the code to test alerteDelete
        //instance.alerteDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('alerteGet', function() {
      it('should call alerteGet successfully', function(done) {
        //uncomment below and update the code to test alerteGet
        //instance.alerteGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('alerteList', function() {
      it('should call alerteList successfully', function(done) {
        //uncomment below and update the code to test alerteList
        //instance.alerteList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('alerteUpdate', function() {
      it('should call alerteUpdate successfully', function(done) {
        //uncomment below and update the code to test alerteUpdate
        //instance.alerteUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userCreate', function() {
      it('should call userCreate successfully', function(done) {
        //uncomment below and update the code to test userCreate
        //instance.userCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userDelete', function() {
      it('should call userDelete successfully', function(done) {
        //uncomment below and update the code to test userDelete
        //instance.userDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userGet', function() {
      it('should call userGet successfully', function(done) {
        //uncomment below and update the code to test userGet
        //instance.userGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userList', function() {
      it('should call userList successfully', function(done) {
        //uncomment below and update the code to test userList
        //instance.userList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('userUpdate', function() {
      it('should call userUpdate successfully', function(done) {
        //uncomment below and update the code to test userUpdate
        //instance.userUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
